[package]
name = "abstract-ns"
description = """
    Abstract name service traits for use with futures (and tokio)
"""
license = "MIT/Apache-2.0"
readme = "README.rst"
keywords = ["dns", "tokio", "name", "service", "discovery"]
homepage = "http://github.com/tailhook/abstract-ns"
documentation = "http://tailhook.github.io/abstract-ns"
version = "0.2.0"
authors = ["paul@colomiets.name"]

[dependencies]
futures = "0.1.1"
quick-error = "1.1.0"
rand = "0.3.14"

[dev-dependencies]
argparse = "0.2.1"

[lib]
name = "abstract_ns"

[workspace]
members = ["ns-std-threaded", "ns-dns-tokio"]
