[package]
name = "ns-std-threaded"
version = "0.1.0"
authors = ["Paul Colomiets <paul@colomiets.name>"]
workspace = '../'

[dependencies]
futures = "0.1.1"
futures-cpupool = "0.1.1"
abstract-ns = { path="../" } #"0.2.0"

[dev-dependencies]
argparse = "0.2.1"
